[package]
name = "day-thirteen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_utils = { path = "../aoc_utils" }
clap = { version = "4.0.27", features = ["derive"] }
slab_tree = "0.3.2"

